// Learn layer, English, final text (requirements P6, domain-pack section 4.4 T1-T25). Plain-language explanations of the terms the app
// shows. Authored text: the user's own numbers are filled in by code (src/learn/explain.js), never written here. Worked examples say
// "example numbers only" and state no stop level, risk percent or size as advice (W5, AC-P6.3). Sources are the [F] and [S] pages of the
// domain pack; the wording was written for this app from them (AC-P6.5). T25 is the app's own explanation.
// `source.section` (added for T26 onward) names the document and section a definition comes from.
// scope 'learn' in src/review/guard.js applies to every text; `cfd` is a legal-review W9 text pinned by hash (scope 'legal').
export const EXAMPLE_ONLY = 'Example numbers only.';

export const ENTRIES = [
  { id: 'T1', slug: 'r', title: 'R', plain: 'R is the amount you lose if a trade reaches the stop you planned for it. Results are counted in multiples of it.',
    steps: ['You plan a trade so that reaching the stop costs 100. Then 1R = 100.', 'The trade ends with +200. That is +2R.', 'It ends with −50 instead. That is −0.5R.'], source: { tag: 'F', url: 'https://crosstrade.io/learn/performance-metrics/r-multiple' } },
  { id: 'T2', slug: 'r-multiple', title: 'R-multiple', plain: 'An R-multiple is a trade’s profit or loss divided by its 1R. +2R means the trade made twice the amount that was at risk. When a stop is filled beyond its price the result can be below −1R.',
    steps: ['Net result +150, 1R = 100: 150 ÷ 100 = +1.5R.', 'Net result −120, 1R = 100: −120 ÷ 100 = −1.2R.'], source: { tag: 'F', url: 'https://crosstrade.io/learn/performance-metrics/r-multiple' } },
  { id: 'T3', slug: 'expectancy', title: 'Expectancy', plain: 'Expectancy is the average result of a trade, in R. It comes from the win rate and from the average size of the wins and the losses. It rests on the trades you have, so a few trades give a shaky number.',
    steps: ['40% of trades win 2R and 60% lose 1R.', '0.40 × 2R − 0.60 × 1R = +0.2R per trade.'], source: { tag: 'F', url: 'https://crosstrade.io/learn/performance-metrics/r-multiple' } },
  { id: 'T4', slug: 'drawdown', title: 'Drawdown', plain: 'Drawdown is how far the account fell from its highest point. The maximum drawdown is the largest such fall in the period, from the peak to the lowest point after it.',
    steps: ['The account peaks at 12,000 and later reaches 9,600.', 'The fall is 2,400, which is 20% of the peak.'], source: { tag: 'F', url: 'https://www.tradezella.com/blog/drawdown-recovery' } },
  { id: 'T5', slug: 'recovery-gain', title: 'Recovery gain', plain: 'Recovery gain is the gain needed to get back to the previous peak. It is always larger than the loss in percent: a 50% fall needs a 100% gain.',
    steps: ['A fall from 12,000 to 9,600 is 20%.', 'Getting back to 12,000 takes 12,000 ÷ 9,600 − 1 = 25%.'], source: { tag: 'F', url: 'https://www.tradezella.com/blog/drawdown-recovery' } },
  { id: 'T6', slug: 'win-rate', title: 'Win rate', plain: 'Win rate is the number of winning trades divided by the number of closed trades. It says nothing about how large the wins and the losses were. A trade that ends at exactly zero is neither a win nor a loss.',
    steps: ['4 winners in 10 closed trades is a win rate of 40%.'], source: { tag: 'S', url: 'https://www.babypips.com/forexpedia/win-rate' } },
  { id: 'T7', slug: 'profit-factor', title: 'Profit factor', plain: 'Profit factor is total profit divided by total loss. Above 1.0 the trades made a net profit. With no losing trade it is not defined, so the app shows no number.',
    steps: ['Winners add up to 600 and losers to 400.', '600 ÷ 400 = 1.5.'], source: { tag: 'S', url: 'https://crosstrade.io/learn/performance-metrics/profit-factor' } },
  { id: 'T8', slug: 'risk-reward', title: 'Risk-reward ratio', plain: 'The risk-reward ratio compares what a trade could gain with what it could lose, for example 3 to 1. It is a plan for one trade, not a result.',
    steps: ['A target that is 300 away and a stop that is 100 away give 3 to 1.'], source: { tag: 'S', url: 'https://www.ig.com/en/risk-management/risk-reward' } },
  { id: 'T9', slug: 'position-sizing', title: 'Position sizing', plain: 'Position sizing is choosing how many shares, coins or lots to trade so that reaching the stop costs an amount you chose. Both the amount and the stop are your own choices.',
    steps: ['You choose to accept a loss of 100 if the stop is reached.', 'The entry is 50 and the stop is 48, so each share risks 2.', '100 ÷ 2 = 50 shares.'], source: { tag: 'F', url: 'https://www.cmcmarkets.com/en/forex/forex-lot-sizes' } },
  { id: 'T10', slug: 'market-order', title: 'Market order', plain: 'A market order buys or sells right away at the price the market shows. The price you get can differ from the price you saw.', source: { tag: 'S', url: 'https://www.investor.gov/introduction-investing/investing-basics/how-stock-markets-work/types-orders' } },
  { id: 'T11', slug: 'limit-order', title: 'Limit order', plain: 'A limit order buys or sells only at your price or at a price that suits you more. It may not be filled at all.', source: { tag: 'S', url: 'https://www.investor.gov/introduction-investing/investing-basics/how-stock-markets-work/types-orders' } },
  { id: 'T12', slug: 'stop-order', title: 'Stop (stop-loss) order', plain: 'A stop order becomes a market order once your stop price is reached, to limit a loss. It can be filled beyond the stop price, which is why a result can be below −1R.', source: { tag: 'S', url: 'https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins-15' } },
  { id: 'T13', slug: 'bid-ask-spread', title: 'Bid, ask and spread', plain: 'The bid is the highest price a buyer offers and the ask is the lowest price a seller accepts. The gap between them is the spread, and it is a cost of every trade.', source: { tag: 'S', url: 'https://en.wikipedia.org/wiki/Bid%E2%80%93ask_spread' } },
  { id: 'T14', slug: 'slippage', title: 'Slippage', plain: 'Slippage is the difference between the price you expected and the price you got.', steps: ['A stop at 48 is filled at 47.60.', 'The slippage is 0.40 per share.'], source: { tag: 'S', url: 'https://en.wikipedia.org/wiki/Slippage_(finance)' } },
  { id: 'T15', slug: 'leverage-margin', title: 'Leverage and margin', plain: 'Leverage is borrowing to control a bigger position than your cash. Margin is the deposit that backs it. Losses are counted on the whole position, so they can be larger than the deposit.', source: { tag: 'S', url: 'https://www.kraken.com/learn/leverage-trading-crypto' } },
  { id: 'T16', slug: 'liquidation', title: 'Liquidation', plain: 'Liquidation is when the broker or exchange closes a leveraged position by force because the margin has run low.', source: { tag: 'S', url: 'https://www.kraken.com/learn/leverage-trading-crypto' } },
  { id: 'T17', slug: 'pip', title: 'Pip', plain: 'A pip is the smallest usual price step in forex: 0.0001, or 0.01 for pairs quoted in yen.', steps: ['EUR/USD moves from 1.0850 to 1.0800: that is 50 pips.'], source: { tag: 'S', url: 'https://www.cmcmarkets.com/en/forex/forex-lot-sizes' } },
  { id: 'T18', slug: 'lot', title: 'Lot', plain: 'A lot is a standard forex trade size: 100,000 units. A mini lot is 10,000 units and a micro lot is 1,000.', source: { tag: 'F', url: 'https://www.cmcmarkets.com/en/forex/forex-lot-sizes' } },
  { id: 'T19', slug: 'funding-rate', title: 'Funding rate', plain: 'The funding rate is a periodic payment between the holders of long and short positions in a perpetual crypto contract, usually every 8 hours. Depending on its sign you pay it or receive it.', source: { tag: 'F', url: 'https://www.binance.com/en/blog/futures/what-are-funding-fees-in-binance-futures-6595842576313788144' } },
  { id: 'T20', slug: 'swap', title: 'Swap (rollover)', plain: 'A swap is the interest charged or paid for holding a forex position past the daily cut-off, which is 5 pm New York time.', source: { tag: 'S', url: 'https://www.forex.com/en-us/help-and-support/rollover/' } },
  { id: 'T21', slug: 'paper-trading', title: 'Paper trade', plain: 'A paper trade is a practice trade with pretend money. It leaves out real fills, real costs and the feeling of having money at stake, so a paper result can differ from what the same trades would have made with real money. The app keeps paper and real trades apart.', source: { tag: 'S', url: 'https://www.cmcmarkets.com/en-gb/trading-strategy/what-is-paper-trading' } },
  { id: 'T22', slug: 'revenge-trading', title: 'Revenge trading', plain: 'Revenge trading is a name traders use for trading fast and large to win back a loss. The app does not label people; it shows when a trade was opened soon after a losing close and asks what was going on.', source: { tag: 'F', url: 'https://crosstrade.io/learn/trading-psychology/revenge-trading' } },
  { id: 'T23', slug: 'overtrading', title: 'Overtrading', plain: 'Overtrading is a name traders use for taking more trades than good setups justify. The app shows days with more trades than your own median and lets you compare them with your plan.', source: { tag: 'S', url: 'https://crosstrade.io/learn/trading-psychology/revenge-trading' } },
  { id: 'T24', slug: 'disposition-effect', title: 'Disposition effect', plain: 'The disposition effect is the tendency to sell winning positions early and to keep losing ones for longer. The app shows the average holding time of your winners and of your losers.', source: { tag: 'S', url: 'https://en.wikipedia.org/wiki/Disposition_effect' } },
  { id: 'T25', slug: 'sample-size', title: 'Sample size', plain: 'Sample size is the number of trades a figure rests on. With few trades a figure can change a lot from one trade to the next, so the app shows n beside each figure and a note when n is small. This explanation is the app’s own.', source: { tag: 'H', url: null } },
  // T26 onward (integration round): terms the app itself shows. Sources: requirements.md definitions and architecture.md sections 3 and 5.1
  // (tag H, the app's own explanation) and domain-pack.md sections 2.2 and 5.1 (tag S). `section` names where the definition is written.
  { id: 'T26', slug: 'realised-unrealised', title: 'Realised and unrealised P&L', plain: 'Realised P&L is the result of trades that are closed. Unrealised P&L is the result of a position that is still open. The app shows only realised results: an open trade is listed with its count and enters no statistic, and no price feed is used.',
    source: { tag: 'H', url: null, section: 'requirements.md, S3 closed-trade set' } },
  { id: 'T27', slug: 'gross-net', title: 'Gross and net P&L', plain: 'Gross P&L is the price result of a trade before costs. Net P&L is gross minus fees and minus funding or swap paid, plus funding or swap received. Statistics use net P&L unless they say gross.',
    steps: ['Price result 210.00, fees 3.00, no funding.', 'Net = 210.00 − 3.00 = 207.00.'], source: { tag: 'H', url: null, section: 'requirements.md, S1 and S2; domain-pack.md 5.4' } },
  { id: 'T28', slug: 'equity-curve', title: 'Equity curve', plain: 'The equity curve is the starting balance plus the running total of net P&L, with one point for each closed trade in the order they closed. Deposits and withdrawals are not points on it.',
    source: { tag: 'H', url: null, section: 'requirements.md, S10' } },
  { id: 'T29', slug: 'rule-following-rate', title: 'Rule-following rate', plain: 'The rule-following rate is the number of closed trades marked as following your plan divided by the number of closed trades that carry a mark. The count of trades with no mark is shown beside it.',
    steps: ['5 trades marked followed, 2 marked off plan, 3 with no mark.', 'The rate is 5 ÷ 7 = 71%, with 3 unmarked beside it.'], source: { tag: 'H', url: null, section: 'requirements.md, AC-P2.4' } },
  { id: 'T30', slug: 'broker-check', title: 'Broker check', plain: 'After an import you can type your broker\'s own figure for a period. The app compares it with its own total for the same period and lists the trades that may explain a difference. A difference nothing accounts for is shown as unexplained; it is never folded into fees or another figure.',
    source: { tag: 'H', url: null, section: 'architecture.md, 5.1 import check and broker check' } },
  { id: 'T31', slug: 'held-out-trade', title: 'Held-out trade', plain: 'A held-out trade is left out of every statistic until you answer a question about it, for example a closing fill whose opening trade is not in the file. The number of held-out trades shows on every statistics screen. A trade you exclude stays in the journal and is flagged.',
    source: { tag: 'H', url: null, section: 'requirements.md, A2 import checks and questions' } },
  { id: 'T32', slug: 'stop-slippage-r', title: 'Stop slippage in R', plain: 'A stop order becomes a market order when its price is reached, so it can be filled beyond the stop price. The result is then below −1R. The app shows the part caused by the fill past the stop and the part caused by fees, and does not clip the result to −1R.',
    steps: ['Entry 50, stop 48, 50 shares: 1R = 100.', 'The stop fills at 47.60 and fees are 2.00: net −122.00, which is −1.22R.', '−1.22R = −1 − 0.20 (fill past the stop) − 0.02 (fees).'], source: { tag: 'S', url: 'https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins-15', section: 'domain-pack.md, 2.2 stop placement; requirements.md, S8' } },
  { id: 'T33', slug: 'broker-account-currency', title: 'Broker account and display currency', plain: 'A broker account is an account you name, with its own base currency. Every trade belongs to one. Each trade\'s result is rounded once, in the base currency of its account. Figures that add several accounts use the display currency you choose, at the rate stored or typed for each account.',
    source: { tag: 'H', url: null, section: 'requirements.md, working terms; architecture.md, 3.1' } },
  { id: 'T34', slug: 'day-cut-off', title: 'Day cut-off', plain: 'Daily figures, weeks and weekdays use one time zone you declare and a day cut-off hour, 00:00 by default. A trade that closes just before midnight in one zone can fall on the next day in another, so changing the zone or the cut-off changes those figures and the screen says so.',
    steps: ['A trade closes at 22:30 UTC on 4 March.', 'In Athens (UTC+2) that is 00:30 on 5 March, so the calendar counts it on 5 March.'], source: { tag: 'H', url: null, section: 'requirements.md, S13; domain-pack.md, 5.1 (crypto row: the day is a convention)' } },
  { id: 'T35', slug: 'forex-session', title: 'Forex session', plain: 'Forex trades around the clock, and traders name the parts of the day by the main market that is open: Sydney, Tokyo, London and New York, plus the overlap of London and New York. The app labels the session of each entry by the clock, following daylight saving in London and New York. It only labels; it does not rank sessions.',
    source: { tag: 'S', url: 'https://www.babypips.com/tools/forex-market-hours', section: 'domain-pack.md, 5.1 sessions and hours; architecture.md, 3.2 S12' } },
  // AC-P6.4: the CFD loss rate appears once, in this wording, with no number (legal-review W9, Q1.6).
  { id: 'CFD', slug: 'cfd-loss-rate', title: 'CFD accounts', scope: 'legal', plain: 'Regulators require CFD providers to publish the share of retail accounts that lose money with them; the figures are provider-specific and are usually a majority. Check your provider\'s current figure.',
    source: { tag: 'F', url: 'https://www.esma.europa.eu/sites/default/files/library/esma35-43-1000_additional_information_on_the_agreed_product_intervention_measures_relating_to_contracts_for_differences_and_binary_options.pdf' } },
];
